### ISSUE TITLE
Improve tower targeting

### ISSUE THREAD

**Issue by sdiaz7** [NestorTejero/ES2016A#162]
### Refining Tower Targeting Behavior:
- Towers target nearest target, and update their priorities if an enemy is getting close to the player's base
- Projectiles are shot from the turret's cannon, or equivalent
- Automatic target switching when current target is out of range or killed

### Definition of Done
- All description bullet points are satisfied
- Turrets correctly update their target
- Projectiles travel in the air and not through the ground

**Initial Estimate: 4 Hours**

**Comment by Nerucius** [comment]
Opened branch [dev_Issue162](https://github.com/NestorTejero/ES2016A/tree/dev_Issue162) with 1 new commit.

**Commit 3503886da8b9dd03f361f3a38f9383c0533d7159**
- Turrets now target smoothly
- Turrets target the nearest enemy, not just the first one in range
- Turret range decreased to 35 from 200
- **Bug** Projectiles despawn inmediately after spawining

Estimated Time Left: 3

**Comment by Nerucius** [comment]
Commits on branch [dev_Issue162](https://github.com/NestorTejero/ES2016A/tree/dev_Issue162):
- New Prefab structure for towers
- Projectiles now coming from tower muzzle
- Enemy Prefab restructured, Collider is now contained on the root GameObject instead of in the Mesh

**Pull Request at #180**

Issue is done. Final time 6 hours

**Comment by Nerucius** [comment]
Merged at #180
