### ISSUE TITLE
Integrate blood texture when the enemy dies.

### ISSUE THREAD

**Issue by mgonzafe91** [NestorTejero/ES2016A#257]
La rama será compartida con el Team A que realiza la Issue #233: Crear y mejorar texturas de sangre.

**Definition of Done:**
- Blood prefab defined as a plane with a blood texture.
- After being hit, enemies spawn at least one blood prefab.
- Object spawned on the ground, near the X-Z position where the hit occurred.
- Blood dissapears after N seconds. N assignable through Inspector. Default value: N=2 seconds.
- Blood stain size proportional to damage suffered.

DEPRECATED: Blood stain spawned at death last more than those spawned when being hit.

**Estimated time:** 3 hours

**Branch:** [dev_Issue233](../tree/dev_Issue233)

**Pull request:** #264

**Comment by sdiaz7** [comment]
I've uploaded the blood prefab. Since I do not dispose of the blood texture yet, I am using ashes texture, that being a distinguishable one.

**Comment by sdiaz7** [comment]
I've made some adjustements to the definition of done. When hit, the stain will appear near the impact position. The scatter is generated randomly.

The changes have increased the number of hours needed for the issue to be completed.

**Comment by ezendirak** [comment]
Blood texture updated. #233

**Comment by sdiaz7** [comment]
Last commit updates EnemyBehavior so that it performs blood spawning as described at DoD. Blood prevalence is not yet accessible through the Inspector. I'm considering moving some of the code to a new script BloodBehavior.

**Comment by sdiaz7** [comment]
Small stains caused by low-damaging bullet projectiles:
![image](https://cloud.githubusercontent.com/assets/17719241/21281885/a1b6b816-c3f0-11e6-97c7-6550aac52687.png)

Blood stain caused by heavy-hitting missile projectile:
![image](https://cloud.githubusercontent.com/assets/17719241/21281926/db7e0068-c3f0-11e6-9039-1891d2eddbb3.png)

**Comment by sdiaz7** [comment]
Added BloodBehavior, which is responsible for depleting blood object.  It also stores some relevant information: blood prevalence, blood maximum and minimum size.

**Comment by sdiaz7** [comment]
For now, I've abandoned the idea of death stain due to some difficulties with the code. If I wanted to implement such feature, I would have to choose one of the following options, none of them appealing:
- Bloating EnemyBehavior with new public variables for stain prevalence
- Storing such variables at BloodBehavior, having to access to them from EnemyBehavior
- Create 2 separate prefabs, one for death stain and another for hit stain

Since a hit must occur for an enemy to die, and that hit will already spawn a stain, I consider that the gains for implementation do not compensate for the effort.

**Comment by sdiaz7** [comment]
Branch approved and integrated. Issue closed and moved to DONE.
