### ISSUE TITLE
Fix bug with tower placement when a different tower is selected

### ISSUE THREAD

**Issue by Nerucius** [NestorTejero/ES2016A#90]

**Comment by agonzatr17** [comment]
**Definition**: When tower placing the player can cancell the tower placement by using right click. When tower placing, if the player clicks on the HUD do the action of the HUD (p.e. buttons), instead of placing the tower. Script to look PlacingTower/TowerPlacement

**Definition of DONE**:
- Player can cancell tower placement
- Tower is not placed if clicking over the HUD.

**Comment by dannylarrea** [comment]
**Modified script**: TowerPlacement
